tab_spaces = 4
max_width = 75
comment_width = 75
wrap_comments = true

group_imports = "StdExternalCrate"
imports_granularity = "One"
reorder_imports = true
reorder_modules = true

merge_derives = true
